spring:
  profiles:
    active: DEVELOP
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/meetroom
    username: meetroom
    password: meetroom
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1;
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
  flyway:
    enabled: false
    encoding: UTF-8
    locations: classpath:/db/flyway/migration/
    validate-on-migrate: true
    baseline-on-migrate: true
server:
  servlet:
    context-path: /meetroom
    port: 8080
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - configprops
