spring:
  profiles:
    active: PRODUCTION

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - configprops
#meetroom reservation properties
meetroom:
  minimum-reservation-value: 30 #in minutes
  maximum-reservation-value: 1440 #24h in minutes

manage-pages:
  pages:
    - name: Manage users
      path: users
      description: "Manage users: register, edit, disable users. Manage user roles and reset password."
      icon: fas fa-user-cog
---

spring:
  profiles: DEVELOP
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/meetroom
    username: meetroom
    password: meetroom
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1;
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  flyway:
    enabled: false
    encoding: UTF-8
    locations: classpath:/db/flyway/migration/
    validate-on-migrate: true
    baseline-on-migrate: true

server:
  servlet:
    context-path: /meetroom
  port: 8030

---

spring:
  profiles: PRODUCTION
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-75-231-215.eu-west-1.compute.amazonaws.com:5432/d67dhfrv46bibi #change it in VM options
    username: oddotruckbompv
    password: ab55ddeb91fed362a903c593f23da9a5059a58f5d1ec5f827f40a81e212f975f
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1;
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:/db/flyway/migration/
    validate-on-migrate: true
    baseline-on-migrate: true

server:
  servlet:
    context-path: /
  port: 80


---

#Profile clone of PRODUCTION, except using local database
spring:
  profiles: LOCAL
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/meetroom_local
    username: meetroom
    password: meetroom
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1;
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:/db/flyway/migration/
    validate-on-migrate: true
    baseline-on-migrate: true

server:
  servlet:
    context-path: /
  port: 8030